#!/usr/bin/env python3
"""Compile a per-house floorplan config into a Lovelace picture-elements card.

Usage:
    python generate.py houses/<house>

Reads ``<house>/config.yaml`` and writes ``<house>/generated/floorplan.yaml``,
a ``vertical-stack`` holding one ``picture-elements`` card per floor. The
generic ``floor-switcher.js`` reads the hidden ``floorplan-meta`` marker in
each card to build the floor buttons and toggle visibility.

The generator is house-agnostic: everything specific to a home lives in its
``config.yaml`` and floor images.
"""
import sys
from pathlib import Path

import yaml

DEFAULT_STYLE = {
    "icon_scale": 1.35,
    "background": "rgba(255, 255, 255, 0.3)",
}

# Translate offsets for state-labels stacked around an icon anchor.
LABEL_SLOTS = {
    "top": "scale(0.8) translate(-63.5%, -105%)",
    "top-secondary": "scale(0.65) translate(-80%, -124%)",
    "bottom": "scale(0.8) translate(-63.5%, 30%)",
    "bottom-secondary": "scale(0.65) translate(-80%, 60%)",
}


def build_entity_elements(item, style):
    """Turn one config entry into one or more picture-elements elements."""
    if "service" in item:
        return [_service_button(item)]

    has_labels = bool(item.get("labels"))
    elements = [_state_icon(item, style, badge=has_labels)]
    if has_labels:
        elements.extend(_state_labels(item))
    return elements


def _anchor_style(item):
    return {"left": item["left"], "top": item["top"]}


def _state_icon(item, style, badge=False):
    element = {
        "type": "state-icon",
        "entity": item["entity"],
        "style": {
            **_anchor_style(item),
            "background-color": style["background"],
        },
    }
    if badge:
        # Pill shape with room for stacked labels (thermostats, sensors...).
        element["style"]["border-radius"] = "999px"
        element["style"]["transform"] = "scale(1) translate(-50%, -50%)"
        element["style"]["padding-top"] = "10px"
    else:
        element["style"]["border-radius"] = "50%"
        element["style"]["transform"] = (
            f"scale({style['icon_scale']}) translate(-50%, -50%)"
        )
    element["tap_action"] = {"action": item.get("tap_action", "toggle")}
    return element


def _state_labels(item):
    labels = []
    for label in item["labels"]:
        slot = label.get("position", "top")
        style = {
            **_anchor_style(item),
            "border-radius": "50%",
            "transform": LABEL_SLOTS.get(slot, LABEL_SLOTS["top"]),
        }
        if "opacity" in label:
            style["opacity"] = label["opacity"]
        element = {"type": "state-label", "entity": item["entity"], "style": style}
        if "attribute" in label:
            element["attribute"] = label["attribute"]
        labels.append(element)
    return labels


def _service_button(item):
    button = {
        "type": "service-button",
        "service": item["service"],
        "style": {
            **_anchor_style(item),
            "background-color": "rgba(255, 255, 255, 0.3)",
            "border-radius": "20px",
            "line-height": "50px",
        },
    }
    if "service_data" in item:
        button["service_data"] = item["service_data"]
    return button


def build_floor_card(floor, style):
    """Build one picture-elements card for a floor, prefixed with a meta marker."""
    title = f"floorplan-meta:{floor['id']}:{floor['name']}"
    if floor.get("default"):
        title += ":default"

    marker = {"type": "icon", "icon": "mdi:floor-plan", "title": title,
              "style": {"display": "none"}}

    elements = [marker]
    for item in floor.get("entities", []):
        elements.extend(build_entity_elements(item, style))

    return {"type": "picture-elements", "image": floor["image"], "elements": elements}


def build_card(config):
    """Build the vertical-stack card holding every floor."""
    style = {**DEFAULT_STYLE, **config.get("style", {})}
    cards = [build_floor_card(floor, style) for floor in config["floors"]]
    return {"type": "vertical-stack", "cards": cards}


def load_config(path):
    with open(path, encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def generate(house_dir):
    house_dir = Path(house_dir)
    config = load_config(house_dir / "config.yaml")
    card = build_card(config)

    out_dir = house_dir / "generated"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "floorplan.yaml"
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("# Generated by core/generate.py — do not edit by hand.\n")
        yaml.safe_dump(card, handle, allow_unicode=True, sort_keys=False)
    return out_path


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 1
    out_path = generate(argv[1])
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
