blueprint:
  name: Stelpro – Sync outside temperature
  description: >
    Push an outdoor temperature (from a weather entity) to multiple Stelpro
    Z-Wave thermostats using Z-Wave JS `invoke_cc_api`.
    Based on https://community.home-assistant.io/t/stzw402-display-outdoor-temperature/151989/13
  domain: automation
  input:
    temperature_input:
      name: Outdoor temperature entity
      selector:
        entity:
          domain: weather
    thermostats:
      name: Thermostats
      description: Select one or more Stelpro thermostats
      selector:
        device:
          integration: zwave_js
          multiple: true

variables:
  temperature_input: !input temperature_input
  thermostats: !input thermostats

trigger:
  - platform: state
    entity_id: !input temperature_input
    attribute: temperature
  - platform: time_pattern
    hours: "/3"

action:
  - repeat:
      for_each: "{{ thermostats }}"
      sequence:
        - service: zwave_js.invoke_cc_api
          target:
            device_id: "{{ repeat.item }}"
          data:
            command_class: 49 # Sensor Multilevel
            method_name: sendReport
            endpoint: 0
            parameters:
              - 1 # scale (°C)
              - 0 # ?
              - "{{ state_attr(temperature_input, 'temperature') | round(1, default=0) }}" # actual temperature

mode: single
