blueprint:
  name: Litter box reminder
  description: Send a notification to the assigned person to clean the litter box.
  domain: automation
  input:
    days_since_last_cleanup:
      name: Days since last cleanup input number
      selector:
        entity:
          domain: input_number
    person_select:
      name: Person selector
      selector:
        entity:
          domain: input_select
    clean_button:
      name: Clean button
      description: Reset counter and change assignee
      selector:
        entity:
          multiple: true
          domain:
            - input_button
            - binary_sensor
    who_is_button:
      name: Who is button
      description: Tell which person is next for the litter
      selector:
        entity:
          multiple: true
          domain:
            - input_button
            - binary_sensor
    days_threshold:
      name: Days threshold before sending a notification
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
          unit_of_measurement: days

trigger_variables:
  person_select: !input person_select

variables:
  person: "{{ states(person_select) }}"
  days_since_last_cleanup: !input days_since_last_cleanup
  days_threshold: !input days_threshold

trigger:
  - platform: template
    id: time
    value_template: "{{ ((as_timestamp(now()) - as_timestamp(states[person_select].last_updated)) / (60 * 60)) | int > 0 and ((as_timestamp(now()) - as_timestamp(states[person_select].last_updated)) / (60 * 60)) | int % 24 < 1 }}"
  - platform: state
    id: clean_button
    entity_id: !input clean_button
  - platform: state
    id: who_is_button
    entity_id: !input who_is_button

action:
  - choose:
      - conditions:
          - condition: trigger
            id: time
        sequence:
          - service: input_number.increment
            target:
              entity_id: !input days_since_last_cleanup
      - conditions:
          - condition: trigger
            id: who_is_button
        sequence:
          - service: tts.cloud_say
            data:
              entity_id: media_player.kitchen_speaker
              message: "Hi, it is {{person}}'s turn to clean the litter box."
              language: en-CA
              options:
                gender: female
      - conditions:
          - condition: trigger
            id: clean_button
        sequence:
          - service: "notify.mobile_app_{{ person }}_phone"
            data:
              message: clear_notification
              data:
                tag: litter_box
          - &RESET_COUNT
            service: input_number.set_value
            data:
              value: 0
            target:
              entity_id: !input days_since_last_cleanup
          - &PING_GOOGLE_HOME
            service: tts.cloud_say
            data:
              entity_id: media_player.kitchen_speaker
              message: "Hi, {{person}} has cleaned the litter box."
              language: en-CA
              options:
                gender: female
          - &RESET_SELECT
            service: input_select.select_next
            target:
              entity_id: !input person_select
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ float(states(days_since_last_cleanup)) >= float(days_threshold) }}"
          - condition: template
            value_template: '{{ is_state("person." + person, "home") }}'
        sequence:
          - service: "notify.mobile_app_{{ person }}_phone"
            data:
              title: 🐈 Cat litter box
              message: "It's been {{ int(states(days_since_last_cleanup)) }} days since last cleanup. Time to do it!"
              data:
                tag: litter_box
                persistent: true
                actions:
                  - action: LITTER_CONFIRM
                    title: I cleaned it up!
                  - action: DISMISS
                    title: Do tomorrow
          - wait_for_trigger:
              - platform: event
                event_type: mobile_app_notification_action
                event_data:
                  action: LITTER_CONFIRM
          - <<: *RESET_COUNT
          - <<: *PING_GOOGLE_HOME
          - <<: *RESET_SELECT
mode: restart
