## To add in configuration.yaml
# sensor:
#   - platform: template
#     sensors:
#       cat_litter:
#         friendly_name: "State"
#         value_template: >-
#           {% if states.counter.poopy_counter.state == '0' %}
#             Clean
#           {% elif states.counter.poopy_counter.state == '1' %}
#             A little dirty
#           {% elif states.counter.poopy_counter.state == '2' %}
#             Could be changed
#           {% else %}
#             Need to be changed
#           {% endif %}
# counter:
#   poopy_counter:
#     name: "Number of days since last change"
#     initial: 0
#     step: 1
#     icon: mdi:paw
# input_select:
#   who_clean:
#     name: "Who will clean it"
#     options:
#      - Eric
#      - Carolanne
#     initial: Eric
#     icon: mdi:panda

- id: cat_litter_days_counter
  alias: Cat Litter Days Counter
  trigger:
    platform: time
    at: "00:00:00"
  action:
    service: counter.increment
    entity_id: counter.poopy_counter

- id: cat_litter_warning
  alias: Cat Litter Poopy Warning
  trigger:
    platform: state
    entity_id: counter.poopy_counter
  condition:
    condition: numeric_state
    entity_id: counter.poopy_counter
    above: 1
  action:
    - service: persistent_notification.create
      data:
        notification_id: "cat_notif"
        message: "{{ states.input_select.who_clean.state }}, it is your turn!"
        title: "The litter box must be changed"
    - service: notify.html5
      data_template:
        target: "{{ states.input_select.who_clean.state | lower }}phone"
        message: It's been {{ states('counter.poopy_counter') }} days since the last change
      data:
        title: Clean the litter box
        data:
          tag: "notification-about-litter-box"
          vibrate: false
          actions:
            - title: Done
              action: "reset_poopy_counter"
            - title: Dismiss
              action: ""

- alias: IFTTT litter box webhook
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: reset_poopy_counter
  action:
    service: script.reset_poopy_counter

- alias: HTML5 push notification litter box cleaned clicked
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: reset_poopy_counter
  action:
    service: script.reset_poopy_counter
