esphome:
  name: espirreceiver
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret hass_ip
  username: !secret hass_username
  password: !secret hass_password

# Enable logging
logger:

ota:
  password: !secret ota_password

remote_receiver:
  pin:
    number: D5
    inverted: true
    mode: INPUT_PULLUP
  dump: lg

binary_sensor:
  - platform: remote_receiver
    name: "Remote play button"
    lg:
      data: 0xFE8016E9
      nbits: 32
  - platform: remote_receiver
    name: "Remote pause button"
    lg:
      data: 0xFE80E619
      nbits: 32
  - platform: remote_receiver
    name: "Remote stop button"
    lg:
      data: 0xFE809669
      nbits: 32
  - platform: remote_receiver
    name: "Remote backward button"
    lg:
      data: 0xFE8056A9
      nbits: 32
  - platform: remote_receiver
    name: "Remote forward button"
    lg:
      data: 0xFE80D629
      nbits: 32
  - platform: remote_receiver
    name: "Remote fast-backward button"
    lg:
      data: 0xFE8036C9
      nbits: 32
  - platform: remote_receiver
    name: "Remote fast-forward button"
    lg:
      data: 0xFE80B649
      nbits: 32
  - platform: remote_receiver
    name: "Remote previous preset button"
    lg:
      data: 0xFE807A84
      nbits: 32
  - platform: remote_receiver
    name: "Remote next preset button"
    lg:
      data: 0xFE80DA24
      nbits: 32
  - platform: remote_receiver
    name: "Remote red button"
    lg:
      data: 0x5EA103FD
      nbits: 32
  - platform: remote_receiver
    name: "Remote green button"
    lg:
      data: 0x5EA1837D
      nbits: 32
  - platform: remote_receiver
    name: "Remote yellow button"
    lg:
      data: 0x5EA143BD
      nbits: 32
  - platform: remote_receiver
    name: "Remote blue button"
    lg:
      data: 0x5EA1C33D
      nbits: 32
  - platform: remote_receiver
    name: "Remote top menu button"
    lg:
      data: 0x5EA105FB
      nbits: 32
  - platform: remote_receiver
    name: "Remote home button"
    lg:
      data: 0xFE806699
      nbits: 32
  - platform: remote_receiver
    name: "Remote pop-up menu button"
    lg:
      data: 0x5EA125DB
      nbits: 32
