esphome:
  name: esplightremote
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret hass_ip
  username: !secret hass_username
  password: !secret hass_password

# Enable logging
logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      inverted: True
      mode: INPUT_PULLUP
    name: "Light remote button 1"
  - platform: gpio
    pin:
      number: D3
      inverted: True
      mode: INPUT_PULLUP
    name: "Light remote button 2"
  - platform: gpio
    pin:
      number: D4
      inverted: True
      mode: INPUT_PULLUP
    name: "Light remote button 3"