esphome:
  name: esp_curtains
  platform: ESP8266
  board: nodemcuv2
  on_boot:
    then:
      - delay: 2s
      - stepper.report_position:
          id: my_stepper
          position: 0
      - stepper.set_target:
          id: my_stepper
          target: 30000
  on_loop:
    then:
      if:
        condition:
          lambda: 'return id(my_stepper).current_position == 30000;'
        then:
          - delay: 2s
          - stepper.set_target:
              id: my_stepper
              target: 5000
      # - servo.write:
      #     id: curtains
      #     level: -100.0%

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.214
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-RGB-Lights Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_curtains_password

# Enable over-the-air updates
ota:
  password: !secret esp_curtains_password

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D5
    pin_b: D6
    pin_c: D7
    pin_d: D8
    max_speed: 500 steps/s
    acceleration: 50 steps/s^2
    deceleration: 50 steps/s^2

# servo:
#   - id: curtains
#     output: sg_90
#     min_level: 5%
#     idle_level: 7.5%
#     max_level: 10%

# output:
#   - platform: esp8266_pwm
#     id: sg_90
#     pin: D4
#     frequency: 50 Hz
