- id: chell_charging_auto  # <-- Required for editor to work.
  alias: Charge Cellphone
  trigger:
    platform: state 
    entity_id: switch.cell_charger
    from: 'off'
    to: 'on'
    for:
      hours: 1
      minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.cell_charger

# Simple button switch for the lights in the kitchen
- id: toggle_kitchen_lights
  alias: Kitchen Lights Toggle
  trigger:
    platform: state 
    entity_id: binary_sensor.kitchen_switch
    from: 'on'
    to: 'off'
  action:
    service: light.toggle
    entity_id: light.kitchen_rgb_lights

- id: turn_off_fan
  alias: Turn Off Fan at Night When Cold
  trigger:
    platform: state 
    entity_id: switch.fan
    from: 'off'
    to: 'on'
    for:
      hours: 3
  action:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: numeric_state
          entity_id: sensor.yr_temperature
          below: 18
    - service: switch.turn_off
      entity_id: switch.fan

- id: media_player_turn_off_rgb
  alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.chromecast_hd
      from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: light.turn_off
      entity_id: light.kitchen_rgb_lights

- id: media_player_turn_on_rgb
  alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.chromecast_hd
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: light.turn_on
      entity_id: light.kitchen_rgb_lights
      data:
        effect: "ColorFade Slow"


# For theme selection
- alias: Set theme at startup
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: frontend.set_theme
    data:
      name: darkcyan

- alias: Default theme during day
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'above_horizon'
  action:
    service: frontend.set_theme
    data:
      name: default

- alias: Dark theme during night
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  action:
    service: frontend.set_theme
    data:
      name: darkcyan