homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  customize: !include customized.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Disable safe warnings
logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical
    homeassistant.components.camera: critical

# Enables configuration UI
config:

# Server security config
http:
  api_password: !secret http_password
  base_url: !secret domain
  ssl_certificate: !secret ssl_fullchain
  ssl_key: !secret ssl_privkey
  ip_ban_enabled: True
  login_attempts_threshold: 5
  # trusted_networks:
  #   - 127.0.0.1
  #   - ::1
  #   - 192.168.0.0/24

ifttt:
  key: !secret ifttt_key

# Text to speech
tts:
  platform: google

# Embedded Broker Server
mqtt:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# digital_ocean:
#   access_token: !secret digital_ocean_access_token

binary_sensor:
  - platform: rpi_gpio
    bouncetime: 10
    ports:
      21: Kitchen Switch
  # - platform: digital_ocean
  #   droplets:
  #     - 'ubuntu-vps'

sensor:
  # Https certificates validation
  - platform: cert_expiry
    host: rasp.ericmatte.me
    name: rasp.ericmatte.me
  - platform: cert_expiry
    host: ericmatte.me
    name: ericmatte.me
  # Weather Prediction
  - platform: yr
    monitored_conditions:
      - temperature
  - platform: moon
  # Raspberry Pi Monitor
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
      - type: disk_use_percent
        arg: /home
      - type: disk_free
        arg: /home
  # Teksavvy
  - platform: rest
    scan_interval: 43200
    resource: !secret teksavvy_api
    headers:
      TekSavvy-APIKey: !secret teksavvy_api_key
    name: Internet Download
    value_template: '{{ value_json["value"][0]["OnPeakDownload"] }}'
    unit_of_measurement: Go
  - platform: rest
    scan_interval: 43200
    resource: !secret teksavvy_api
    headers:
      TekSavvy-APIKey: !secret teksavvy_api_key
    name: Usage End Date
    value_template: '{{ value_json["value"][0]["EndDate"].split("T")[0] }}'

camera:
 - platform: mjpeg
   mjpeg_url: http://localhost:8081
   name: Live Cam

switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      eric_desktop:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch1_on
        code_off: !secret zap_switch1_off
        signal_repetitions: 20
      caro_desktop:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch2_on
        code_off: !secret zap_switch2_off
        signal_repetitions: 20
      fan:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch3_on
        code_off: !secret zap_switch3_off
        signal_repetitions: 20
      rainbow_lights:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch4_on
        code_off: !secret zap_switch4_off
        signal_repetitions: 20
      cell_charger:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch5_on
        code_off: !secret zap_switch5_off
        signal_repetitions: 20

light:
  - platform: mqtt_json
    name: "Kitchen RGB Lights"
    state_topic: "home-assistant/rgb"
    command_topic: "home-assistant/rgb/set"
    brightness: true
    color_temp: true
    rgb: true
    effect: true
    effect_list: ["ColorFade Slow", "ColorFade Fast", "Flash"]
    optimistic: false
    qos: 0

script:
  good_night:
    sequence:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: switch.turn_off
        entity_id:
          - switch.eric_desktop
          - switch.caro_desktop
          - switch.rainbow_lights
      - service: media_player.turn_off
        entity_id:
          - media_player.chromecast_hd
      - service: switch.turn_on
        entity_id:
          - switch.cell_charger

automation: !include automation.yaml

group: !include groups.yaml
