homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Toronto
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

http:
  base_url: !secret pi_domain
  ssl_certificate: !secret ssl_fullchain
  ssl_key: !secret ssl_privkey
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24

logger:
  default: warning
  # logs:
  #   homeassistant.components.switch.command_line: critical

config:

system_health:

mqtt:
  discovery: true
  broker: 127.0.0.1
  username: !secret mqtt_username
  password: !secret mqtt_password

# Google Assistant Integration
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
  entity_config:
    switch.google_home:
      expose: false
    switch.flux:
      expose: false

#device_tracker:
#  - platform: bluetooth_tracker
#    new_device_defaults:
#      track_new_devices: false
#   - platform: nmap_tracker
#     interval_seconds: 30
#     consider_home: 480
#     track_new_devices: yes
#     hosts: 192.168.1.200-201

ifttt:
  key: !secret ifttt_key

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_server_key
    gcm_sender_id: !secret gcm_sender_id

tts:
  platform: google

zwave:
  usb_path: /dev/ttyACM0

updater:

discovery:

conversation:

history:

logbook:

sun:

cast:
  media_player:
    - host: 192.168.1.197

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  # Https certificates validation
  - platform: cert_expiry
    scan_interval: 43200 # 2 times/day
    host: !secret pi_domain
    name: !secret pi_domain
  # Weather Prediction
  - platform: yr
    scan_interval: 3600 # 1 time/hour
    monitored_conditions:
      - temperature
  - platform: moon
  # Raspberry Pi Monitor
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: disk_use_percent
        arg: /home
      - type: disk_free
        arg: /home
  # Google Home Text Display
  - platform: mqtt
    state_topic: "home-assistant/google-home"
    name: "Google Input Text:"
  - platform: mqtt
    state_topic: "home-assistant/google-home-datetime"
    name: "Recognized at"
  # Cat Litter Checker
  - platform: template
    sensors:
      cat_litter:
        friendly_name: "State"
        value_template: >-
          {% if states.counter.poopy_counter.state == '0' %}
            Clean
          {% elif states.counter.poopy_counter.state == '1' %}
            A little dirty
          {% elif states.counter.poopy_counter.state == '2' %}
            Could be changed
          {% else %}
            Need to be changed
          {% endif %}

# camera:
#  - platform: mjpeg
#    mjpeg_url: http://localhost:8081
#    name: Live Cam

switch:
  - platform: flux
    mode: mired
    disable_brightness_adjust: True
    lights:
      - light.dining_room
      # - light.hue_light_1
  - platform: tplink
    host: !secret hs200_1
  - platform: tplink
    host: !secret hs200_2
  - platform: rpi_rf
    gpio: 17
    switches:
      eric_desktop:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch1_on
        code_off: !secret zap_switch1_off
        signal_repetitions: !secret zap_signal_repetition
      caro_desktop:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch2_on
        code_off: !secret zap_switch2_off
        signal_repetitions: !secret zap_signal_repetition
      rainbow_lights:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch4_on
        code_off: !secret zap_switch4_off
        signal_repetitions: !secret zap_signal_repetition
      cell_charger_eric:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch5_on
        code_off: !secret zap_switch5_off
        signal_repetitions: !secret zap_signal_repetition
      ac:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch3_on
        code_off: !secret zap_switch3_off
        signal_repetitions: !secret zap_signal_repetition
  - platform: command_line
    switches:
      google_home:
        friendly_name: Google Home
        command_on: sudo systemctl start googlehome.service
        command_off: sudo systemctl stop googlehome.service
        command_state: 'sudo systemctl status googlehome.service --full | grep -oPc "Active: active"'
        # value_template: '{{ value == "1" }}'

light:
  - platform: mqtt
    name: "Kitchen RGB Lights"
    schema: json
    state_topic: "home-assistant/rgb"
    command_topic: "home-assistant/rgb/set"
    brightness: true
    effect_list: ["ColorFade Slow", "ColorFade Fast", "Flash"]
    color_temp: true
    rgb: true
    effect: true
    optimistic: false
    qos: 0

# Poopy counter
counter:
  poopy_counter:
    name: "Number of days since last change"
    initial: 0
    step: 1
    icon: mdi:paw

input_select:
  who_clean:
    name: "Who will clean it"
    options:
     - Eric
     - Carolanne
    initial: Eric
    icon: mdi:panda

binary_sensor:
  - platform: rpi_gpio
    bouncetime: 50
    ports:
      21: Kitchen Switch
      20: Kitchen motion sensor

# Coffee machine
# input_datetime:
#   coffee_time_selector:
#     name: "Time to brew coffee"
#     has_date: false
#     has_time: true

input_boolean:
  kitchen_motion_sensor:
    name: Kitchen motion sensor
    initial: on
    icon: mdi:flash-circle
  walk_in_door_sensor:
    name: Walk-in door sensor
    initial: on
    icon: mdi:flash-circle
#   coffee_activator:
#     name: "Brew coffee on selected time"
#     initial: off
#     icon: mdi:coffee

# Imports
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
