homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Disable safe warnings
logger:
  default: warning
  logs:
    homeassistant.components.switch.command_line: critical
    requests.packages.urllib3.connectionpool: critical
    homeassistant.components.camera: critical
    aiohttp.server: critical
    hbmqtt.broker: critical

# Enables configuration UI
config:

# Server security config
http:
  api_password: !secret http_password
  base_url: !secret domain
  ssl_certificate: !secret ssl_fullchain
  ssl_key: !secret ssl_privkey
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24

# device_tracker:
#   - platform: nmap_tracker
#     interval_seconds: 30
#     consider_home: 480
#     track_new_devices: yes
#     hosts: 192.168.1.200-201

ifttt:
  key: !secret ifttt_key

# Text to speech
tts:
  platform: google

# Embedded Broker Server
mqtt:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

recorder:
  # Delete events and states older than 2 weeks
  purge_days: 14

digital_ocean:
  access_token: !secret digital_ocean_access_token

binary_sensor:
  - platform: rpi_gpio
    bouncetime: 10
    ports:
      21: Kitchen Switch
  - platform: digital_ocean
    droplets:
      - 'ubuntu-vps'

sensor:
  # Https certificates validation
  - platform: cert_expiry
    host: !secret pi_domain
    name: !secret pi_domain
  - platform: cert_expiry
    host: !secret personal_domain
    name: !secret personal_domain
  # Weather Prediction
  - platform: yr
    monitored_conditions:
      - temperature
  - platform: moon
  # Raspberry Pi Monitor
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
      - type: disk_use_percent
        arg: /home
      - type: disk_free
        arg: /home
  # Teksavvy
  - platform: rest
    scan_interval: 43200
    resource: !secret teksavvy_api
    headers:
      TekSavvy-APIKey: !secret teksavvy_api_key
    name: Internet Download
    value_template: '{{ value_json["value"][0]["OnPeakDownload"] }}'
    unit_of_measurement: Go
  - platform: rest
    scan_interval: 43200
    resource: !secret teksavvy_api
    headers:
      TekSavvy-APIKey: !secret teksavvy_api_key
    name: Usage End Date
    value_template: '{{ value_json["value"][0]["EndDate"].split("T")[0] }}'
  # Google Home Text Display
  - platform: mqtt
    state_topic: "home-assistant/google-home"
    name: "Google Input Text:"
  # Cat Litter Checker
  - platform: template
    sensors:
      cat_litter:
        friendly_name: "State"
        value_template: >-
          {% if states.counter.poopy_counter.state == '0' %}
            Clean
          {% elif states.counter.poopy_counter.state == '1' %}
            A little dirty
          {% elif states.counter.poopy_counter.state == '2' %}
            Could be changed
          {% else %}
            Need to be changed
          {% endif %}

camera:
 - platform: mjpeg
   mjpeg_url: http://localhost:8081
   name: Live Cam

switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      eric_desktop:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch1_on
        code_off: !secret zap_switch1_off
        signal_repetitions: 20
      caro_desktop:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch2_on
        code_off: !secret zap_switch2_off
        signal_repetitions: 20
      fan:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch3_on
        code_off: !secret zap_switch3_off
        signal_repetitions: 20
      rainbow_lights:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch4_on
        code_off: !secret zap_switch4_off
        signal_repetitions: 20
      cell_charger:
        protocol: !secret zap_protocol
        pulselength: !secret zap_pulselength
        code_on: !secret zap_switch5_on
        code_off: !secret zap_switch5_off
        signal_repetitions: 20
  - platform: command_line
    switches:
      google_assistant:
        friendly_name: Google Assitant
        command_on: sudo systemctl start googlehome.service
        command_off: sudo systemctl stop googlehome.service
        command_state: sudo systemctl status googlehome.service
        value_template: '{{ not is_state(value, NULL) and "Active: active (running)" in value }}'
      live_cam:
        friendly_name: Live Camera
        command_on: sudo systemctl start motion.service
        command_off: sudo systemctl stop motion.service
        command_state: sudo systemctl status motion.service
        value_template: '{{ not is_state(value, NULL) and "Active: active (running)" in value }}'

light:
  - platform: mqtt_json
    name: "Kitchen RGB Lights"
    state_topic: "home-assistant/rgb"
    command_topic: "home-assistant/rgb/set"
    brightness: true
    color_temp: true
    rgb: true
    effect: true
    effect_list: ["ColorFade Slow", "ColorFade Fast", "Flash"]
    optimistic: false
    qos: 0

counter:
  poopy_counter:
    name: "Number of days since last change"
    initial: 0
    step: 1
    icon: mdi:paw

automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
