name: Storybook Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-after-pr-closed:
    name: Cleanup After PR Closed
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.ref}}"
        if: startsWith(github.ref, 'refs/pull')
      - run: echo "$GH"
        env:
          GH: ${{ toJson(github) }}
  cleanup-after-pr-closed2:
    if: startsWith(github.ref, 'refs/pull')
    name: Cleanup After PR Closed2
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.ref}}"
      - run: echo "$GH"
        env:
          GH: ${{ toJson(github) }}


